"""Routing helpers and algorithms for the interactive workbench."""

from .segments import (
    add_port_stub_segment,
    build_routes_from_paths,
    merged_axis_segments,
    merged_route_axis_segments,
    metric_route_segments,
    point_is_segment_endpoint,
    route_segments_from_path,
)
from .metrics import (
    count_ordered_route_turns,
    count_route_short_pieces,
    count_segment_clearance_conflicts,
    count_segment_crossings,
    count_segment_overlaps,
    count_solution_short_pieces,
    count_solution_turns,
    merged_route_piece_lengths,
    segment_metric_dir,
)
from .hit_testing import (
    find_route_at_point,
    find_route_hit_at_point,
    selected_pin_names,
)
from .clearance import (
    add_machine_clearance_weights,
    add_route_interaction_weights,
    add_static_clearance_weights,
    block_terminal_node_edges,
    buffered_radius_mm,
    machine_edge_clearance_distances,
    normalized_edge,
    required_clearance_mm,
    route_axis_records,
    set_block_weight,
    static_clearance_distances,
    weighted_edge_cost,
)
from .flow import (
    add_edge,
    build_pin_min_cost_flow_network,
    min_cost_flow,
    positive_flow_edges,
    small_pin_target_specs,
    source_start_nodes,
    trace_flow_path,
)
from .scoring import (
    RouteScoreWeights,
    route_conflict_summary,
    route_quality_counts,
    route_quality_warnings,
    score_routes,
    total_route_length,
    total_route_length_m,
)
from .search import (
    line_graph_dir_from_points,
    ordered_small_room_names,
    path_physical_length,
    run_super_sink_line_graph_search,
    run_super_sink_state_astar,
    terminal_node_indices,
    target_heuristic,
)
from .terminal_validity import terminal_validity_entries
from .validation import append_allowed_region_warning, count_segments_outside_allowed_region

__all__ = [
    "RouteScoreWeights",
    "add_edge",
    "add_machine_clearance_weights",
    "append_allowed_region_warning",
    "build_pin_min_cost_flow_network",
    "add_port_stub_segment",
    "block_terminal_node_edges",
    "add_route_interaction_weights",
    "add_static_clearance_weights",
    "buffered_radius_mm",
    "build_routes_from_paths",
    "count_ordered_route_turns",
    "count_route_short_pieces",
    "count_segment_clearance_conflicts",
    "count_segment_crossings",
    "count_segment_overlaps",
    "count_segments_outside_allowed_region",
    "count_solution_short_pieces",
    "count_solution_turns",
    "find_route_at_point",
    "find_route_hit_at_point",
    "merged_axis_segments",
    "merged_route_axis_segments",
    "merged_route_piece_lengths",
    "metric_route_segments",
    "min_cost_flow",
    "line_graph_dir_from_points",
    "machine_edge_clearance_distances",
    "normalized_edge",
    "ordered_small_room_names",
    "path_physical_length",
    "point_is_segment_endpoint",
    "positive_flow_edges",
    "route_conflict_summary",
    "route_segments_from_path",
    "run_super_sink_line_graph_search",
    "run_super_sink_state_astar",
    "required_clearance_mm",
    "route_axis_records",
    "route_quality_counts",
    "route_quality_warnings",
    "score_routes",
    "selected_pin_names",
    "segment_metric_dir",
    "set_block_weight",
    "static_clearance_distances",
    "source_start_nodes",
    "small_pin_target_specs",
    "target_heuristic",
    "terminal_node_indices",
    "terminal_validity_entries",
    "total_route_length",
    "total_route_length_m",
    "trace_flow_path",
    "weighted_edge_cost",
]
