from __future__ import annotations

from pathlib import Path

from .schema import ConfigCatalog, ConfigParameter


DWELLING_EXPORT_ROOT = Path.home() / "Documents" / "Dwelling-export"


SALUBRIDAD_PARAMETERS = (
    ConfigParameter(
        key="SALUBRIDAD.SOLVER.GRAPH.REGULAR_GRID_SPACING_MM",
        default=200,
        reason="solver",
        unit="mm",
        description="Regular routing grid spacing.",
        legacy_names=("GRID_SPACING",),
    ),
    ConfigParameter(
        key="SALUBRIDAD.SOLVER.GRAPH.HANNAN_SCAFFOLD_SPACING_MM",
        default=600,
        reason="solver",
        unit="mm",
        description="Static connectivity scaffold for dynamic Hannan axes.",
        legacy_names=("HANNAN_SCAFFOLD_SPACING",),
    ),
    ConfigParameter(
        key="SALUBRIDAD.SOLVER.GRAPH.GRID_EPSILON_MM",
        default=200,
        reason="solver",
        unit="mm",
        description="Core-like epsilon offset for geometry and connector axes.",
        legacy_names=("CORE_EPSILON_GRID_MM", "SALUBRIDAD.EPSILON"),
    ),
    ConfigParameter(
        key="DOMAIN.GEOMETRY.WALL_THICKNESS_MM",
        default=150,
        reason="domain",
        unit="mm",
        description="Displayed and filtered wall thickness.",
        legacy_names=("WALL_THICKNESS",),
    ),
    ConfigParameter(
        key="SALUBRIDAD.FEASIBILITY.ROUTING.MIN_DISTANCE_TO_WALL_MM",
        default=100,
        reason="feasibility",
        unit="mm",
        description="Minimum routing-node and edge clearance from walls and allowed boundaries.",
        also_affects=("solver",),
        legacy_names=("ROUTING_WALL_CLEARANCE_MM",),
    ),
    ConfigParameter(
        key="SALUBRIDAD.FEASIBILITY.TERMINALS.MIN_DISTANCE_TO_WALL_MM",
        default=100,
        reason="feasibility",
        unit="mm",
        description="Minimum terminal candidate clearance from room boundaries.",
        legacy_names=("TERMINAL_REGULATION_CLEARANCE_MM",),
    ),
    ConfigParameter(
        key="SALUBRIDAD.FEASIBILITY.TERMINALS.ROOM_BOUNDARY_BUFFER_MM",
        default=150,
        reason="feasibility",
        unit="mm",
        description="Additional room-boundary buffer for air terminal candidate nodes.",
        legacy_names=("BUFFER_ROOM_TERMINALES_AIRE_MM",),
    ),
    ConfigParameter(
        key="PATINEJOS.FEASIBILITY.CLEARANCE.NON_SHAFT_DUCT_MM",
        default=200,
        reason="feasibility",
        unit="mm",
        description="Hard clearance from shafts for ducts that are not entering the shaft.",
        legacy_names=("PATINEJO_CLEARANCE_MM",),
    ),
    ConfigParameter(
        key="PATINEJOS.SOLVER.ENTRY.SEARCH_RADIUS_MM",
        default=700,
        reason="solver",
        unit="mm",
        description="Search envelope used to discover shaft entry candidates.",
        legacy_names=("SHAFT_ENTRY_SEARCH_MM",),
    ),
    ConfigParameter(
        key="PATINEJOS.PERFORMANCE.ENTRY.MAX_CANDIDATES",
        default=16,
        reason="performance",
        description="Maximum shaft entry candidates to keep.",
        legacy_names=("SHAFT_ENTRY_MAX_CANDIDATES",),
    ),
    ConfigParameter(
        key="SALUBRIDAD.DOMAIN.MACHINE.OZEO_FLAT.BODY_WIDTH_MM",
        default=410,
        reason="domain",
        unit="mm",
        description="Ozeo Flat body width used for display and collision checks.",
        legacy_names=("MACHINE_BODY_W",),
    ),
    ConfigParameter(
        key="SALUBRIDAD.DOMAIN.MACHINE.OZEO_FLAT.BODY_HEIGHT_MM",
        default=460,
        reason="domain",
        unit="mm",
        description="Ozeo Flat body height used for display and collision checks.",
        legacy_names=("MACHINE_BODY_H",),
    ),
    ConfigParameter(
        key="SALUBRIDAD.DOMAIN.MACHINE.OZEO_FLAT.OVERALL_WIDTH_MM",
        default=511,
        reason="domain",
        unit="mm",
        description="Ozeo Flat connector envelope width.",
        legacy_names=("MACHINE_OVERALL_W",),
    ),
    ConfigParameter(
        key="SALUBRIDAD.DOMAIN.DUCTS.SMALL_DIAMETER_MM",
        default=90,
        reason="domain",
        unit="mm",
        description="Bathroom, toilet, and washroom duct diameter.",
        legacy_names=("MACHINE_SMALL_DUCT_D",),
    ),
    ConfigParameter(
        key="SALUBRIDAD.DOMAIN.DUCTS.LARGE_DIAMETER_MM",
        default=125,
        reason="domain",
        unit="mm",
        description="Kitchen and shaft duct diameter.",
        legacy_names=("MACHINE_LARGE_DUCT_D",),
    ),
    ConfigParameter(
        key="SALUBRIDAD.FEASIBILITY.CONNECTORS.SMALL_STUB_LENGTH_MM",
        default=100,
        reason="feasibility",
        unit="mm",
        description="Small connector outside projection used for valid access.",
        also_affects=("solver",),
        legacy_names=("SMALL_PIN_STUB_LENGTH",),
    ),
    ConfigParameter(
        key="SALUBRIDAD.FEASIBILITY.CONNECTORS.LARGE_STUB_LENGTH_MM",
        default=250,
        reason="feasibility",
        unit="mm",
        description="Large connector outside projection used for valid access.",
        also_affects=("solver",),
        legacy_names=("LARGE_PIN_STUB_LENGTH",),
    ),
    ConfigParameter(
        key="SALUBRIDAD.FEASIBILITY.CLEARANCE.DUCT_BUFFER_RATIO",
        default=1.05,
        reason="feasibility",
        description="Duct radius inflation factor before clearance tests.",
        also_affects=("solver",),
        legacy_names=("DUCT_BUFFER_RATIO",),
    ),
    ConfigParameter(
        key="SALUBRIDAD.HEURISTIC.PLACEMENT.MACHINE_CLEARANCE_SOFT_MARGIN_MM",
        default=150,
        reason="heuristic",
        unit="mm",
        description="Soft-cost band outside machine-body hard clearance.",
        also_affects=("solver",),
        legacy_names=("MACHINE_CLEARANCE_SOFT_MARGIN_MM",),
    ),
    ConfigParameter(
        key="SALUBRIDAD.SOLVER.COST.BEND_PENALTY_DEFAULT_MM",
        default=4000.0,
        reason="solver",
        unit="mm",
        description="Default cost added when a route changes direction.",
        legacy_names=("C_BEND_DEFAULT",),
    ),
    ConfigParameter(
        key="SALUBRIDAD.UI.CONTROLS.BEND_PENALTY_MIN_MM",
        default=0.0,
        reason="ui",
        unit="mm",
        description="Minimum bend-penalty slider value.",
        legacy_names=("C_BEND_MIN",),
    ),
    ConfigParameter(
        key="SALUBRIDAD.UI.CONTROLS.BEND_PENALTY_MAX_MM",
        default=10000.0,
        reason="ui",
        unit="mm",
        description="Maximum bend-penalty slider value.",
        legacy_names=("C_BEND_MAX",),
    ),
    ConfigParameter(
        key="SALUBRIDAD.SOLVER.COST.CROSSING_PENALTY_MULTIPLIER_DEFAULT",
        default=5.0,
        reason="solver",
        description="Default multiplier applied to bend penalty for crossings.",
        legacy_names=("CROSSING_MULTIPLIER_DEFAULT",),
    ),
    ConfigParameter(
        key="SALUBRIDAD.UI.CONTROLS.CROSSING_MULTIPLIER_MIN",
        default=0.0,
        reason="ui",
        description="Minimum crossing multiplier slider value.",
        legacy_names=("CROSSING_MULTIPLIER_MIN",),
    ),
    ConfigParameter(
        key="SALUBRIDAD.UI.CONTROLS.CROSSING_MULTIPLIER_MAX",
        default=12.0,
        reason="ui",
        description="Maximum crossing multiplier slider value.",
        legacy_names=("CROSSING_MULTIPLIER_MAX",),
    ),
    ConfigParameter(
        key="COLLISIONS.SOLVER.OVERLAP_BLOCK_WEIGHT",
        default=1e9,
        reason="solver",
        description="Effective hard block for exact same-axis duct overlaps.",
        legacy_names=("OVERLAP_BLOCK_WEIGHT",),
    ),
    ConfigParameter(
        key="SALUBRIDAD.HEURISTIC.DUCTS.MIN_PIECE_FACTOR_DEFAULT",
        default=1.05,
        reason="heuristic",
        description="Default factor used to warn and score minimum physical duct piece length.",
        also_affects=("solver",),
        legacy_names=("MIN_PIECE_FACTOR_DEFAULT",),
    ),
    ConfigParameter(
        key="SALUBRIDAD.UI.CONTROLS.MIN_PIECE_FACTOR_MIN",
        default=0.50,
        reason="ui",
        description="Minimum minimum-piece factor slider value.",
        legacy_names=("MIN_PIECE_FACTOR_MIN",),
    ),
    ConfigParameter(
        key="SALUBRIDAD.UI.CONTROLS.MIN_PIECE_FACTOR_MAX",
        default=2.00,
        reason="ui",
        description="Maximum minimum-piece factor slider value.",
        legacy_names=("MIN_PIECE_FACTOR_MAX",),
    ),
    ConfigParameter(
        key="IO.PATHS.DWELLING_EXPORT_ROOT",
        default=DWELLING_EXPORT_ROOT,
        reason="paths",
        description="Local root used for optional dwelling export data.",
        legacy_names=("DWELLING_EXPORT_ROOT",),
    ),
    ConfigParameter(
        key="IO.PATHS.DWELLING_EXPORT_DB",
        default=DWELLING_EXPORT_ROOT / "data" / "dwellings.sqlite",
        reason="paths",
        description="Optional real-dwelling SQLite database path.",
        legacy_names=("REAL_DWELLING_DB",),
    ),
    ConfigParameter(
        key="SALUBRIDAD.INPUT.PREFERRED_SHAFT_INSTALLATION",
        default="Sal",
        reason="input",
        description="Preferred installation label used to choose shaft metadata.",
        legacy_names=("PREFERRED_SHAFT_INSTALLATION",),
    ),
    ConfigParameter(
        key="SYSTEM.UI.FPS",
        default=20,
        reason="ui",
        description="Pygame frame-rate target.",
        legacy_names=("FPS",),
    ),
)


def build_sal_catalog() -> ConfigCatalog:
    return ConfigCatalog(SALUBRIDAD_PARAMETERS)


SALUBRIDAD_DEFAULTS = build_sal_catalog()
